### PR TITLE
Tools page

### PR DESCRIPTION
**Pull request by NasirAbdullahSyed**

### CODE REVIEW

**Comment by SaadBazaz** [comment]
https://github.com/SaadBazaz/omni/assets/51885228/db44acfe-c6f7-42a9-8c85-5da427eda36c

Problems in scroll. Most likely snap interfering. Also UI looks different on Mac.

**Review by SaadBazaz — CHANGES_REQUESTED** [review]
Match spec. 
Fix scrolling.

**Comment by NasirAbdullahSyed** [comment]
> Match spec. Fix scrolling.

Scroll bug fixed
Reviewed UI on Zohair bhai's Mac, seems fine.

Inform me if you see any differences, I will start working on game dev.

**Review by SaadBazaz — APPROVED** [review]
Changes:
- Fixed mobile responsiveness
- Made according to Figma spec
- Improved code structure.

**Pull request merged**
